# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20170110_0803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempUserProfile',
            new_name='UserProfile',
        ),
    ]
