# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import registrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20170116_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=registrations.models.avatar_upload_to, verbose_name='Изображение'),
        ),
    ]
